### ISSUE TITLE
[Request] Please Provide an Initial Release Version Number 

### ISSUE THREAD

**Issue by dhtseany** [StreamController/streamcontroller-plugin-tools#1]
Hello, I'm working on porting your StreamController project over to Arch Linux and as this project is one of your direct dependencies I'll need to get it published as well. Can you please push a Release for easier packaging of streamcontroller-plugin-tools on my side? Thanks!

**Comment by Core447** [comment]
Added the current version as `2.0.0`. Is this enough? Let me know if you need anything else

**Comment by dhtseany** [comment]
Perfect, thank you, that generated the .tar.gz files I was looking for! 

The AUR package for streamcontroller-plugin-tools is here: https://aur.archlinux.org/packages/streamcontroller-plugin-tools-git

Once I sort out the logistics of a native install of StreamController I'll publish it as well. I'm all set, I look forward to helping more in the future! Thanks for your help!

**Comment by Core447** [comment]
> Once I sort out the logistics of a native install of StreamController I'll publish it as well. I'm all set, I look forward to helping more in the future! Thanks for your help!

Thank you! Nice work!
